### PR TITLE
Update runtime, make use of Zypak

### LINKED ISSUE #4: A new version of the XMind 2020 is released
The XMind 2020 10.3.1 (202101132117) is available on 14 January 2021: https://www.xmind.net/download/.

### PR DESCRIPTION
**Pull request by lionirdeadman**
Fix #4

### CODE REVIEW

**Comment by lionirdeadman** [comment]
Forgot to update the appdata, done now.

**Comment by cheese** [comment]
Tested the new build. It works well.

But I don't actively maintain this package any more. I want to authorize you to push directly but don't know how to do that[1].

[1] https://discourse.flathub.org/t/how-to-add-another-maintainer/1494

**Comment by lionirdeadman** [comment]
I just noticed the script still has the discord appid, fixed. Oops.

I don't use this application but I can maintain it.

**Comment by nedrichards** [comment]
> Tested the new build. It works well.
> 
> But I don't actively maintain this package any more. I want to authorize you to push directly but don't know how to do that[1].
> 
> [1] https://discourse.flathub.org/t/how-to-add-another-maintainer/1494

I have added @lionirdeadman to have write access to the repo. Thanks for bringing it up.

**Pull request merged**
